### ISSUE TITLE
Scrolling directly to 'flags' results in incorrect scroll position 

### ISSUE THREAD

**Issue by ReneS1991** [serebrov/emoji-mart-vue#49] opened 2019-07-11 08:13 UTC
Hi,

First off, thanks for this amazing fast version of emoji-mart-vue! 😄 

When using it in one of my project I noticed that the scrolling to the 'symbols' and 'flags' categories by clicking the category doesn't scroll to the correct height (only on initial load and as first 'click'). In the demo, the problem only occurs when clicking the 'flags' category:

Problem:
![image](https://user-images.githubusercontent.com/17007821/61033171-28cd3c80-a3c3-11e9-9011-9084a8b446cd.png)

What I expect:
![image](https://user-images.githubusercontent.com/17007821/61033484-e5270280-a3c3-11e9-91f3-a131aac5f2b6.png)

It only happens on the initial load, clicking immediately on the category. As mentioned, in my project the bug occurs for both the 'symbols' and 'flags' category, in the demo only for 'flags', but I think it is the same bug. Also as mentioned, when you already clicked on any of the other categories first, it behaves correctly.

In the original demo (emoji-mart-vue) it works correctly.

It is a minor bug and not really bothering me, but a fix for it sometime would be nice of course 😃 

Thanks!

**Comment by serebrov** [comment] 2019-07-11 08:46
@ReneS1991 Thanks, I see the issue and will check it soon. One note for now - the issue is reproduced in the first picker here (https://serebrov.github.io/emoji-mart-vue/), but it works good in the second picker (Custom Search And Preview Templates Example).

I also checked it in the project where I use the component and it also works good, although the look is heavily customized in there, might be something related to CSS.

**Comment by ReneS1991** [comment] 2019-07-11 08:58
Okay cool, thanks for the quick reply! 👍

**Comment by serebrov** [comment] 2019-07-13 21:13
@ReneS1991 The issue is related to vue-virtual-scroller, not 100% sure, but this might be a bug. I found a workaround and published a new (5.4.15) version to npm, please check if it works on your side. 
The scrolling to flags in [demo app](https://serebrov.github.io/emoji-mart-vue/).

**Comment by serebrov** [comment] 2019-08-25 10:20
Hopefully it works now, closing the issue.

**Closed by serebrov** 2019-08-25 10:20 UTC
